### ISSUE TITLE
Implementar SmartMuiDataTable en vistas faltantes

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1541]
Hrs: <hrs>3</hrs>

- [ ] Staff
- [ ] Invites
- [ ] Leads (Form Entry)
- [ ] Cohorts
- [ ] Answers
- [ ] Events

**Comment by Omonroy36** [comment]
Staff - Done
 Invites - Done
 Leads (Form Entry) - Done
 Cohorts - Done
 Answers - Done
 Events - Done

I implemented in every view the SmartUIDataTable, but there is an issue when paginating because every time you try to go to the next page its trying to query "sort" and "like" those queries should only be triggered when you use the search or sort the table not always so this in the SmartUIDataTable should be fixed in order for everything to work properly
