### ISSUE TITLE
assignments.breatheco.de or oldteacher.breatheco.de

### ISSUE THREAD

**Issue by RickRodriguez8080** [4GeeksAcademy/About-4Geeks-Academy#1557]
I was working with a cohort teacher on student progress, using the `assignments.breatheco.de` platform. I noticed that there were only submissions from 2 former students (none from the current group).  The teacher shared their screen and showed the current progress, using `oldteacher.breatheco.de`.  These two platforms are not in sync with one another.  Which one should we be using to keep track of student progress?  Is this going to affect future cohorts coming up this month?

**Comment by alesanchezr** [comment]
The only platform we are using from now on is:
For teachers: teacher.breatheco.de
For students: learn.breatheco.de
For admin: admin.breatheco.de

The new cohorts have all ben using that, the ones that are still using `oldteacher` or `student.breatheco.de` it's because they are the oldest cohort and we were still migrating but that should not happen anymore.
