### ISSUE TITLE
Image preview on markdown files looks blurry on content.breatheco.de

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1636]
Here is an example:
https://content.breatheco.de/en/lesson/making-an-amazing-resume

This is how it looks:
![Screen Shot 2021-08-03 at 3 36 03 PM](https://user-images.githubusercontent.com/426452/128075495-4c934285-b19e-4114-8451-daa56c078e3b.png)

**Comment by ArielCalisaya** [comment]
I have searched everywhere and tried the possible errors but, I could not find a solution to this problem.

apparently this this is a **bug with the height of the image**, since gatsby cannot identify the height of the image (`gatsby-remark-images` replace part of the long image with a blurry copy), I will replace with another image related to the content topic
