### ISSUE TITLE
Upgrade the input type=phone to have users pick country

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1822]
es necesario pedir o el país o el código telefónico del país, es muy dificil contactar con los leads cuando no se registra el lugar de donde viene atuomáticamente porque no sabemos su código telefónico para llamarlo.

La solución es preguntar el país o exigir el código de llamada internacional de ese país.

**Comment by alesanchezr** [comment]
Cual sera la mejor solucion para esto?

Sera que les ponemos un mensaje de error que diga q el numero debe empezar por un mas `+`?

**Comment by victormgomezp** [comment]
Un selector o un campo separado que ponga prefijo o código de país o algo
por el estilo.


| Victor Manuel Gómez Pérez
| Country Manager Spain
| (+34) 684 33 25 81
| www.4GeeksAcademy.com

**Comment by ArielCalisaya** [comment]
The issue is almost finished, but i have some troubles with the new updates and the endpoint

---

- [ ] With the new component `PhoneInput`, we can create masks for each country prefix ('`cl`', '`us`', `'es'`, etc...) in a maskList
```js
    const maskList = [
      {us: '+9\ (999) 999-9999'},
      {cl: '+999 9999 9999'},
      {default: '+999 999 999 999 999'},
    ];
```

>Now when the input receives values it will be formatted according to the selected country
>example with **United States** prefix: `+1 (455) 452-4345`

---

### The problem occurs when sending the input with the formatted values the endpoint does not accept the format

#### Headers:
```bash
Request URL: https://breathecode-cypress.herokuapp.com/v1/marketing/lead
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 3.123.451.102:003
Referrer Policy: strict-origin-when-cross-origin
```

#### Received payload:
```js
{
    first_name: "test",
    email: "cs@gmail.com",
    phone: "+1 (455) 452-4345",
    tag: "request_more_info",
    utm_url: "http://localhost:8000/es/landing/bootcamp-de-programacion-santiago",
    language: "us",
    ...etc,
}
```

![Bootcamp de programación en Santiago de Chile, aprende a programar en 9 o 16 sem y consigue trabajo ](https://user-images.githubusercontent.com/51676628/147374806-41cd9f88-30e8-4b6d-b31c-368864764a9f.png)

@alesanchezr Any solution :thinking: ?

**Comment by alesanchezr** [comment]
no allowing to select the location
