### ISSUE TITLE
Delete survey is giving an error

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1910]
![Screen Shot 2021-10-29 at 3 51 39 PM](https://user-images.githubusercontent.com/426452/139494062-ded02d83-5e24-46fb-b9f7-f52988a0fac1.png)

**Comment by ingindIsrael** [comment]
This issue needs some changes on the backend

![Screen Shot 2021-12-27 at 1 49 52 PM (2)](https://user-images.githubusercontent.com/19786923/147499442-b0b97abd-18ea-4320-b775-e1599b20bf02.png)

<img width="1280" alt="Screen Shot 2021-12-27 at 1 49 52 PM" src="https://user-images.githubusercontent.com/19786923/147499464-46cec3d4-acbf-4557-ad73-79c46d47bf69.png">
 
This commit contains the fix done on survey.jsx (second picture) [https://github.com/ingindIsrael/admin/commit/b182bde6d3c1a37ffe5168cac723394b6b664c2f](https://github.com/ingindIsrael/admin/commit/b182bde6d3c1a37ffe5168cac723394b6b664c2f), but is failing because a cypress test is unstable (this one [https://github.com/ingindIsrael/admin/runs/4644215211?check_suite_focus=true](https://github.com/ingindIsrael/admin/runs/4644215211?check_suite_focus=true))
