### ISSUE TITLE
Media Gallery PDF url not loding (error)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1923]
These files are in the media gallery and the google bucket but the URL gives an error, for example: https://storage.googleapis.com/media-breathecode/3d1d1e250fd6e715dc430c147f4aa71df6cd19e407fc6f15746e598ff20fd3d4

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/224

**Comment by jefer94** [comment]
https://github.com/pytest-dev/pytest/issues/9306

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/225

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/276

**Comment by jefer94** [comment]
The file was save in the cloud like a `application/pdf`
https://console.cloud.google.com/storage/browser/_details/media-breathecode/c2c78e61461b75e99d81b769489f52d365610d0e9f80e69431b0dde3c05660df

The file can't be loaded by the browser because GCS set `Content-Type` as `text/plain`
https://storage.googleapis.com/media-breathecode/c2c78e61461b75e99d81b769489f52d365610d0e9f80e69431b0dde3c05660df
