### ISSUE TITLE
General - Componente de Proyectos (alumnos)

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2047]
En el componente de "Meet Our Alumni and Their Projects" hay un comportamiento que podemos mejorar de cara al usuario y es que, si el usuario le da play a un video de un proyecto pero cambia a otro proyecto (en los bullets), el usuario escuchará de fondo el video al que le dió play aunque ya esté viendo visualizando otro proyecto.

Incluso si le da play a varios videos de varios proyectos y no les da a Pausar, puede escuchar todos los videos solapados, escuchandose al mismo tiempo.

**El comportamiento ideal sería que si un usuario da play al video y cambia para visualizar otro proyecto, el video del proyecto al que le dió play, debería pausarse inmediatamente automáticamente. 

Solo se reproducirá el video, cuando el usuario haya dado play y esté visualizando ese proyecto en particular.**

**Comment by ArielCalisaya** [comment]
The solution to this issue is very complex, since this component contains 2 dependencies with independent 
roles (`react-slick` and `react-youtube`), so it is complex to make it work as expected without creating bugs

Therefore, when changing the state of `showVideo` component, the video will now be paused, so that the user can decide when to start the video.
