### ISSUE TITLE
When a new event is created a new tag must also be created on activecampaign

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2148]
The marketing module is decoupled from the event module, the right way to notify the marketing module when a new event is created is thru the `event_saved` signal ([click here to review it](https://github.com/breatheco-de/apiv2/blob/master/breathecode/events/signals.py#L7)).

- [ ] Receive the signal on the marketing module by adding a receiver into the breathecode.marketing.receivers and make sure to trigger a task (on taskbreathecode.marketing.task) when a new event is created, that task will take care for creating the tag.
- [ ] The new tag will have as slug the event slug but with the word `event` prepended, for example if the event slug is `pitchday-miami-ft-2` the tag will be `event-pitchday-miami-ft-2`
- [ ] The tag must also be added to the breathecode.marketing.models.tag table with the type=EVENT
- [ ] Make sure to unit test

**Comment by alesanchezr** [comment]
Probe y el tag del evento no se esta creando

**Comment by jefer94** [comment]
When we create a tag in active campaign the slug is coming from `tag` key instead of `slug`
![image](https://user-images.githubusercontent.com/3018142/156439141-8693b352-0698-46ab-967e-2bd86cca0fe7.png)

- [ ] Make sure the delete the print inside the client of `acp` and in the task
- [ ] Make get the tag slug from the `tag` key instead of `slug`
