### ISSUE TITLE
There is a weird behavior with the duration when you update the service form several times it becomes NaN

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2470]
<hrs>1</hrs>

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xenogenesis20** [comment]
Found the bug, issue was that the original values object was being mutated in the 'update' function. The input fields are numbers and the function returns a string which is why nothing would show on the input. 
The reason why the 3 durations would disappear when changing the language is because changing the language causes a re-render and the duration values at that point are strings. 
I defined new variables for the durations in the update function as to not mutate the original.

**Comment by xenogenesis20** [comment]
<hrs>1</hrs>
