### ISSUE TITLE
Translation of lesson, practices and code Titles

### ISSUE THREAD

**Issue by Jtoledo88** [4GeeksAcademy/About-4Geeks-Academy#2498]
Hey guys! @alesanchezr  @ArielCalisaya I wanna know, if we can translate this:

![image](https://user-images.githubusercontent.com/32654829/162822901-832839cf-c97c-419c-a9cb-3320f4221ac5.png)

If this possible, tell me how?

**Comment by alesanchezr** [comment]
Not possible, and we are not event ready to be able to translare that, its quite a challenge to be honest because those titles are coming from the syllabus JSON and creating trasnlations will be basically creating a whole different syllabus but in spanish.

Also the maintenance will become a nightmare because every update we do to the syllabus will have to be done in both languages... 

I'm about to cry because idk how to translate these without increasing the workload in 200% from now on...
