### ISSUE TITLE
Markdown breaking, but i don't see any problems in the source

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2531]
It[ looks good on github](https://github.com/breatheco-de/content/blob/master/src/content/lesson/what-is-a-python-list.md#looping-using-a-position) but our MarkdownReader is breaking:

https://4geeks.com/en/syllabus/machine-learning-prework/read/what-is-a-python-list

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/25786234?key=fb09b16ceabf2ca1825546c8d85fb8be&size=orig)

**Comment by ArielCalisaya** [comment]
# There is a format inconsistency with the markdown received and the compiler

Since the `compiler` of `markdown-to-jsx` interprets it as a code block if there is an empty line before it.

Otherwise it will interpret it as inline code

# Preview
![Components-MarkDownParser-Default-⋅-Storybook](https://user-images.githubusercontent.com/51676628/163701690-65d1b352-23af-42cb-aa49-73f9b89521d5.png)
