### ISSUE TITLE
How to clone a project on github

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3078]
## Meta Info

- Github URL: https://github.com/breatheco-de/content/blob/master/src/content/how-to/%5Bdraft%5Dgithub-clone-repository.md
- Number of words: ~800 words
- Asset Type: Lesson, Article, Quiz, Project or Exercise.
- Primary keyword: `github clone repository` (please make sure it's a pre-approved keyword).
- Technologies: `git, github` (only one or more pre-approved technologies, check admin.4geeks.com).

## Additional Info

1. Any recommended approach for the article?

- [ ] What is cloning a project? and why cloning? (max ~200 words as we don't want to scare the user)
- [ ] Very clear steps to reproduce on how to clone from github using the terminal (with code example).
- [ ] Mention that you can clone clone any repository (from other sites) if we have the git URL. (with code example)
- [ ] What is the difference between clone and fork?
- [ ] Very clear steps on the steps needed to fork before cloning
- [ ] How to clone using the github app instead of the terminal.
- [ ] Please, after the article is finished and pre-approved, record a video between 6min and two 12min explanation with all this concepts.

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mentrion the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifts or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] If you have not already, please read [the guide on how to create an article inside the content repository.](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md)

**Comment by rafmanrique** [comment]
1. Any recommended approach for the article?

- [x]  What is cloning a project? and why cloning? (max ~200 words as we don't want to scare the user)

- [x]  Very clear steps to reproduce on how to clone from GitHub using the terminal (with code example).

- [ ] Mention that you can clone any repository (from other sites) if we have the git URL. (with code example)

- [ ]  What is the difference between clone and fork?

- [ ]  Very clear steps on the steps needed to fork before cloning

- [ ]  How to clone using the GitHub app instead of the terminal.

- [ ]  Please, after the article is finished and pre-approved, record a video between 6min and two 12min explanation with all these concepts.

[Github Clone Repository](https://github.com/rafmanrique/content/blob/github-clone-repository/src/content/how-to/%5Bdraft%5Dgithub-clone-repository.md)

**Comment by rafmanrique** [comment]
- [x] Clean HTML code, only use markdown.
- [x] There content is too similar to github's cloning explanation, try explaining in your own words.
- [x] Make sure the article is written by you, with your honest and transparent knowledge and writing.

[Github Clone Repository](https://github.com/rafmanrique/content/blob/github-clone-repository/src/content/how-to/%5Bdraft%5Dgithub-clone-repository.md)

PR: https://github.com/breatheco-de/content/pull/890

**Comment by tommygonzaleza** [comment]
- [ ] Add columns after each list element

**Comment by Lorenagubaira** [comment]
- [ ] Correct the word `Fastes` to `Fastest` in the subheading column of the infobox at the top

**Comment by rafmanrique** [comment]
- [x] Add columns after each list element
- [x] On the How to clone using the GitHub app instead of the terminal it's going from 1 to 3.
- [x]  Correct the word Fastes to Fastest in the subheading column of the infobox at the top
- [x] Clean HTML code, only use markdown.

[Github Clone Repository](https://github.com/rafmanrique/content/blob/github-clone-repository/src/content/how-to/%5Bdraft%5Dgithub-clone-repository.md)

PR: https://github.com/breatheco-de/content/pull/890

**Comment by rafmanrique** [comment]
- [x] In the images located on lines 113 and 117 please change "connected" to "connect".

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
Video: https://www.loom.com/share/03f17fb305704623bb65f0641a5fcb4e
Hrs: <hrs>1</hrs>
