### ISSUE TITLE
Componente para eventos live

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3330]
Diseño figma: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3733%3A9473

A partir de una lista de eventos en vivo:

- [x]  debes pintar el destacado arriba
- [x] Los demas colapsados abajo
- [ ] Los que esten por empezar o ya hayan empezado que latan como un radar, se puede configurar el tiempo que determina que estan por empezar como una variable timedelta en milisegundos, por ejemplo: `startingSoonDelta={3600000}`
- [x] Los eventos vienen con un icono
- [x] Incluirlo en storybooks con todas sus variables parametrizables

<img width="618" alt="Screen Shot 2022-09-21 at 10 13 01 PM" src="https://user-images.githubusercontent.com/426452/191643344-e771702e-35f6-4a99-b541-7c0c3fc03bc8.png">

**Comment by tommygonzaleza** [comment]
Everything is well, icon is not blinking when event is about to start, it could be because none of them are about to start, and I don't know how much time is known as about to start

**Comment by alesanchezr** [comment]
Story

**Comment by tommygonzaleza** [comment]
- [ ] Add property to storybook `liveUrl`.
- [ ] Add property `liveStartsAt` instead of `startsAt`.
- [ ] The first text should's property should be `featureLabel` and the second one `featureReadMoreUrl` (Both should be nullable):
![image](https://user-images.githubusercontent.com/56565994/193943284-df46c225-a3f7-4200-894a-bf5f279a3dc2.png)
- [ ] Use UTC dates/times and localize the date/time to show the data

**Comment by tommygonzaleza** [comment]
Tested and working fine
