### ISSUE TITLE
Include "permissions" array on the payload for `GET /v1/auth/user/me`

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3349]

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/576

**Comment by tommygonzaleza** [comment]
It´s not showing any permissions when the user has superstatus

**Comment by tommygonzaleza** [comment]
It shows the permissions array empty with selected permissions as well

**Comment by jefer94** [comment]
I think is a bad idea have a different behavior between users and superusers, because the superusers generally is the developers generally and the idea is the frontends be the first beta tester of app before it hit production

Also actually we just using the permissions that is in `set_permissions.py` they are linked to the permissions through of groups, the question is, we really want have a table with all the permissions of Django in the frontend? I think we don't want it, and also if in a moment we want to reuse a django permission, that is unlikely to happen, we can add it to a group, and saves in network transfers very much bytes

What is the approach you think we should follow?

**Comment by tommygonzaleza** [comment]
Ohh alright, now I get you, I thought you were trying to retrieve Django's permissions, but you are right I think we should only worry about the permissions through groups, and as you said, if we need to reuse a Django permission we can just add it to a group.

Anyway we can discuss this with Alejandro and ask about the best approach
