### ISSUE TITLE
New pricing component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3467]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5483%3A3160

- [x] The YML information must be added into the location ymls (both langs).
- [x] Every plan will have a name (slug) in the yml
- [x] Once a plan has been selected the infor has to pass to be added into the session as "financing_plan" and then eventually when the student applies to the academy it has to be included in the payload.

**Comment by tommygonzaleza** [comment]
- [ ] Make it more responsive, if the screen is bigger, this is how it looks like: 
![image](https://user-images.githubusercontent.com/56565994/199312712-accd1a5a-e5ad-45c6-9383-43e4668e3a35.png)

**Comment by tommygonzaleza** [comment]
- [ ] Use fixed size by the device in the white container
- [ ] If plans are even, width should be 50%, if they're odd, all of them should have 50% except for the first one who should have 100%
- [ ] The white box should always be a side of the black one, forget about percentages
- [ ] Instead of sending the course plan through the context, send it through the url
