### ISSUE TITLE
The deployment is failling because of node's version

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3642]
The deployment of this repository is failling: https://github.com/4GeeksAcademy/About-4Geeks-Academy 

![image](https://user-images.githubusercontent.com/56565994/201428136-c77151e2-f24e-47cc-96e9-9b4b77146104.png)

**Comment by arnaldoperez** [comment]
Upgrading to node 14 creates a lot of errors, related with the gatsby version (v2) wich is deprecated. The project needs refactor in order to work with a more recent version of its dependencies 
![image](https://user-images.githubusercontent.com/19396163/215571289-c599c814-2615-4e1e-8df7-0571c3e0248f.png)

**Comment by arnaldoperez** [comment]
4 Hours spend in it total

**Comment by tommygonzaleza** [comment]
<hrs>4</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>4</hrs>
