### ISSUE TITLE
Posibilidad de rescatar backlinks con dofollow de los ultimos 6 meses

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4040]
Resulta que según href hemos perdido 95 backlinks con dofollow en los ultimos 6 meses, [aqui puedes ver la lista desde ahref](https://app.ahrefs.com/v2-site-explorer/backlinks/subdomains?followType=dofollow&grouping=group-similar&highlightChanges=30d&history=lost&historyDateRange=6m&limit=50&offset=0&sort=dr&sortDirection=desc&target=4geeksacademy.com%2F) pero tambien te la estoy adjuntando como un archivo para excel.
Te puedes tomar un rato a ver si podemos rescatar alguno de estos links?

[4geeksacademy.com-backlinks-subdomains__2023-01-11_00-03-03.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/10389020/4geeksacademy.com-backlinks-subdomains__2023-01-11_00-03-03.csv)

**Comment by Jsolis4geeks** [comment]
Estuve revisando y parece que Ahrefs tuvo un bug xq esos enlaces se mantienen en muchos casos

**Comment by alesanchezr** [comment]
No te enfoques en los que no se perdieron, si no en los que SI se perdieron a ver como los recatamos.

**Comment by Jsolis4geeks** [comment]
- [ ] This [website](https://fi.co/event/93721-founder-night-out-network-with-local-entrepreneurs.) had a backlink to https://4geeksacademy.com/ on an image on the of their partners, don't what happened if the partnership with them was lost or ended and maybe this is why they deleted the image and the link. We can contact them to ask them if they would like to link and partner with 4 Geeks Academy again.
- [ ] This [website](https://www.mdc.edu/ce/padron/) had a backlink to https://4geeksacademy.com/ given the status of good relations with MDC we could ask them to put the article or an update back on and link to our site.
- [ ] This [website](https://nitter.social.cologne/alesanchezr) and this [one](https://nitter.social.cologne/4GeeksAcademy) had a backlink to https://4geeksacademy.com/ but my Anti Virus marks them as suspicious, so do not recommend trying to take this links back.
- [ ] This [website](https://unitedwaymiami.org/) had a backlink to https://4geeksacademy.com/us/landing/united-way in some sort of partnership, but don't know if the partnership ended, but they updated their website and deleted the backlink leading to 4 Geeks Academy.
- [ ] This [website](http://twtr.domain.glass/search?q=%23codingbootcamp) is some sort of social media platform and had a backlink to http://www.4geeksacademy.com/ but to get it back the one with the login credentials should go and put the post again because I did not saw any signup button. As a side note, this website is not https, it is HTTP, so it is not a backlink of too much relevance.
- [ ] This [website](https://blog2.yerbo.co/blog/como-cuidar-tu-salud-mental-y-productividad-trabajando-remoto-durante-covid-19/) had a backlink to 
- [ ] This [website](url) had a backlink to http://www.4geeksacademy.com/ but this website is deactivted and no longer private.
- [ ] This [website](https://techhubsouthflorida.org/blog/page/4/) was linking to this page https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami but looks like they made an update on the content and decided to delete our link, we could contact them to try to get that link back since they talk about our niche. This is their email: team@techhubsouthflorida.org
- [ ] This [page](https://www.datascience.salon/miami-ml-meetup-week/) was linking to http://www.4geeksacademy.com/ for a meetup but since that meetup was 4 months ago they deleted the backlink to 4 Geeks Academy
- [ ] This [website](https://www.cobuildlab.com/customer-success-stories/jobcore) that was linking to the home page is a 404, we could let them know this so they try to take the page back on. They are linking http://www.4geeksacademy.com/ in  3 other pages.
- [ ] This [website](https://nitter.manerakai.com/search?f=tweets&q=%23LearnToCode) was linking to http://www.4geeksacademy.com/ but the site cant be reached any more
- [ ] This [website](https://www.paudal.com/2022/01/07/experts-in-programming-data-management-and-cybersecurity-are-already-the-most-demanded-technological-profiles/) was linking to https://4geeksacademy.com/es/inicio/ but the article was lost, is now a 404 we could contact them through email to let them know about this issue and we might get that backlink back.
