### ISSUE TITLE
Article is missing

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#4042]
### Bug description

This [article](https://4geeksacademy.com/us/software-engineer-salary/software-engineer-salary-florida) was published one week ago and it was already indexed by Google, the article has now disappeared and on the admin, it is shown as published.

### Steps to reproduce

1 - Identify the article
2 - Identify why the article from the blog is not published on the main site
3 - Fix de Issue

**Comment by alesanchezr** [comment]
@gustavomm19 This is happening because of pagination, [this query](https://github.com/4GeeksAcademy/website-v2/blob/master/src/utils/api.js#L19) is fetching for all the articles but its not specifiying any limit or offset parameters. The API will fetch only 100 by default if you dont specify `limit=100&offset=0`.

I think we need to create a while loop that keeps fetching more and more if the incoming results have a length equal to 100, this is some badly formated pseudo code logic
```js
let allArticles = []
const results = fetch(/academy/assets?limit=100&offset=0);
allArticles.concat(results)

while(results.length === 100){
  const results = fetch(/academy/assets?limit=100&offset=allArticles.length);
  allArticles.concat(results)
}
```
