### ISSUE TITLE
Leer este articulo y presentarle a alejandro un documento con acciones a seguir para cumplir con eso

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4115]
https://ahrefs.com/blog/blog-seo/

**Comment by Jsolis4geeks** [comment]
**1 - Find a Keyword:** Each blog post you write should be optimized for one main keyword, and that keyword should be something that people are actually searching for month after month.

**2. Check search intent:** Is important to understand whether most searchers are looking for a blog post or something else. This is known as assessing [search intent](https://ahrefs.com/blog/search-intent/).

**3. Choose a winning format and angle:** Even if searchers are looking for blog posts, you can’t just write any old post and rank in pole position because searchers are often looking for something specific. You need to figure out what this is to develop a winning format and angle for your post.

Examples: 

- How-to guide
- Step-by-step tutorial
- Opinion piece
- Review
- Comparison

**4. Craft a data-driven outline:** Subheadings often align with subtopics. If you see common subheadings across multiple top-ranking posts for your keyword, it’s probably something that searchers want to know.

**5. Write the post:** It’s finally time to start tapping away on your keyboard to write your first draft.

**How to optimize your blog posts for SEO:**

- Include your keyword in the title
- Keep your title tag short
- Use an evergreen URL
- Craft a compelling meta description
- Optimize images
- Add a table of contents 
- Include ‘linkable snippets’ 
- Add schema markup
- Add internal links

**Note:** We are doing all of this
