### ISSUE TITLE
Sponsored campaign campaign

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4510]
Buscar lista de empresas a las que podemos pagar para que nos publiquen una campaña de email, blog post, etc. Por ejemplo:
collegeconsensus . com (incluirla)
Ignorar a switchup, course report y kareer karma poque ya las hemos utilizado.

- [ ] Redacar template pidiendoles informacion sobre sponsoship opportunities.
- [ ] Buscar lista de paginas potenciales, usualmente las paginas de listados de cursos tienen eso.

**Comment by Jsolis4geeks** [comment]
Created the Campaign with pages: You can check for it [here](https://v2.linkhunter.com/campaigns/aejandro-sanchez-full-stack-developer-course-sponsored-campaign)

Here is the recommended template:

Hello [Name], my name is Alejandro Sanchez, CEO of 4Geeks Academy

We're currently looking for a select group of bloggers to partner with. I wanted to reach out to you since I thought your blog would be a good fit.

We're interested in sponsoring a post on your blog highlighting one of our products: our Full Stack Developer Course.

In regards to pricing, what are your rates for this type of sponsored content?

Looking forward to a mutually beneficial partnership.

Thank you

4Geeks Academy is a premier coding bootcamp with brick & mortar locations and an online presence in multiple countries. We offer lifetime career support, 10 dollars in scholarships, or a money-back guarantee. Our innovative platform, 4Geeks.com, provides interactive coding and instant feedback. We have graduated over 3000 students with an 84% job placement rate, named top 10 by Newsweek and top 35 by CourseReport and Switchup.

Note: Remeber we talked about that this campaign should be sent from your email account to use your Brand in our favor

**Comment by Jsolis4geeks** [comment]
Contacted 2 Agencies for Backlinks, waiting for their response.

PragoMedia 
MotherLink

**Comment by Jsolis4geeks** [comment]
Can also send this campaign under that template:

https://v2.linkhunter.com/campaigns/aejandro-sanchez-full-stack-developer-course-sponsored-campaign

**Comment by Jsolis4geeks** [comment]
Approved fort sending Link Hunter Campaign

Approved one Backlink on MOtherLink from around 350

**Comment by Jsolis4geeks** [comment]
The Two campaigns were sent:

- [ ] https://v2.linkhunter.com//websites/1670610?c=5300&q=prospects
- [ ] https://v2.linkhunter.com/websites/1674642?c=5314&q=prospects


The link selected was this one:



![Image](https://user-images.githubusercontent.com/118853358/224465946-eff094e7-0d52-4781-b945-80cd7cb79a58.png)

**Comment by alesanchezr** [comment]
Buscar listas en españa, mexico, canada, usa y portugal.

**Comment by Jsolis4geeks** [comment]
Comence con USA y la forma mas rentable que me pareció era buscar keywords y sacar las paginas que posicionaban por esas keywords:

[google_us_full-stack-web-develo_serp-overview_2023-03-29_23-18-24.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11107412/google_us_full-stack-web-develo_serp-overview_2023-03-29_23-18-24.csv)
[google_us_machine-learning-engi_serp-overview_2023-03-29_23-18-02.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11107413/google_us_machine-learning-engi_serp-overview_2023-03-29_23-18-02.csv)
[google_us_full-stack-developer_serp-overview_2023-03-29_23-17-22.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11107414/google_us_full-stack-developer_serp-overview_2023-03-29_23-17-22.csv)
[google_us_data-science_serp-overview_2023-03-29_23-36-43.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11107481/google_us_data-science_serp-overview_2023-03-29_23-36-43.csv)

**Comment by Jsolis4geeks** [comment]
Approved for sending on Link Hunter

**Comment by Jsolis4geeks** [comment]
Volvi a hacer este research xq la mayoria de las paginas que se iban a hacer target eran paginas que ofrecian cursos, por lo tanto la posibilidad de que nos enviaran un enalce eran muy pocas, entonces añadi un filtro basado en el DR entre 40 y 70 para llegar a los sitios principales para estas keywords pero dejando de lado Course.ra, Iro.nhack y otros

**Comment by Jsolis4geeks** [comment]
Envié estas 3 campañas para Full Stack Developer, Full Stack Developer Salary y Full Stack Bootcamp:

https://v2.linkhunter.com/websites/1749082?c=5415&amp;q=contacted
https://v2.linkhunter.com/websites/1749339?c=5417&amp;q=contacted
https://v2.linkhunter.com/websites/1749289?c=5418&amp;q=contacted



Serian solo 3 de momento para no sobrecargar la cuenta de email que ya estuvimos a punto de perderlo por spam

**Comment by Jsolis4geeks** [comment]
Don't know why this is closed since this is still missing 3 campaigns.

**Comment by Jsolis4geeks** [comment]
Envié estas 3 campañas para Machine Learning Engineer, Machine Learning Engineer Salary y Machine Learning Engineer Bootcamp:
